Запросы:

1: 
ALTER TABLE TICKET 
ADD NUMBER_VAN BIGINT CHECK (NUMBER_VAN > 0);

UPDATE TICKET SET NUMBER_VAN = (random() * 99 + 1) WHERE true;

2: 
ALTER TABLE WAY_STATION 
ADD PARKING_TIME INTERVAL;

UPDATE WAY_STATION SET PARKING_TIME = (random() * INTERVAL 'P1Y2M') WHERE true;

3:
CREATE TABLE NATURAL_PERSON (
	ID BIGINT PRIMARY KEY,
	LAST_NAME CHARACTER(30),
	NAME CHARACTER(30),
	MIDDLE_NAME CHARACTER(30), --отчество
	PASSPORT_SERIES BIGINT,
	NUMBER_SERIES BIGINT,
	DATE_OF_BIRTH timestamp,
	SEX CHARACTER(30)
);

INSERT INTO NATURAL_PERSON VALUES
(73, 'Дорохов', 'Владимир', 'Александрович', 4953, 543434, '2016-07-22', 'M'),
(74, 'Зубенко', 'Михаил', 'Петрович', 2232, 323200, '2010-05-31', 'M'),
(75, 'Мякина', 'Наталья', 'Валерьевна', 4098, 345623, '1016-01-02', 'Ж')
RETURNING ID;

4:
ALTER TABLE NATURAL_PERSON
ADD CHECK (SEX = 'M' OR SEX = 'Ж'); -- M on inglish:)

5:
CREATE TABLE BUY (
	ID BIGINT PRIMARY KEY,
	TICKET_ID BIGINT REFERENCES TICKET (ID),
	NATURAL_PERSON_ID BIGINT REFERENCES NATURAL_PERSON (ID),
	DATE_OF_PURCHASE timestamp,
	RETURN_DATE timestamp DEFAULT NULL
);

INSERT INTO BUY VALUES
(76, 47, 73, '2023-01-20'),
(77, 48, 74, '2023-02-25'),
(78, 49, 75, '2023-03-27')
RETURNING ID;

6:
ALTER TABLE TICKET
DROP COLUMN STATE;

7:
CREATE TABLE BONUS_CARD (
	ID BIGINT PRIMARY KEY,
	BALANCE BIGINT,
	NUMBER_OF_TRIPS BIGINT
);

INSERT INTO BONUS_CARD VALUES
(79, 10, 2),
(80, 20, 3),
(81, 30, 1)
RETURNING ID;

8:
ALTER TABLE NATURAL_PERSON 
ADD BONUS_CARD_ID BIGINT REFERENCES BONUS_CARD (ID);

UPDATE NATURAL_PERSON SET BONUS_CARD_ID = (random() * 2 + 79) WHERE true;

9:
ALTER TABLE TICKET 
ALTER COLUMN TYPE_WAGON SET DEFAULT 1;

10:
ALTER TABLE WAY_STATION 
ADD DISTANCE BIGINT DEFAULT (5000 * random());

ALTER TABLE WAY_STATION 
ALTER COLUMN DISTANCE DROP DEFAULT;

Правка:
ALTER TABLE BUY 
ALTER COLUMN RETURN_DATE SET DEFAULT NULL;

Демонстрация:
\d+ TICKET;

SELECT PARKING_TIME FROM WAY_STATION;

SELECT * FROM NATURAL_PERSON;

\d+ NATURAL_PERSON;

SELECT * FROM BUY;

SELECT * FROM BONUS_CARD;

SELECT DISTANCE FROM WAY_STATION;

Дополнения:

INSERT INTO TICKET VALUES
(82, 22, 2, 0, 2500, -1)
RETURNING ID;
