Запросы:

1: SELECT t.TYPE_WAGON, COUNT(t.*) FROM JOURNEY j INNER JOIN ROUTE r ON j.ROUTE_ID = r.ID INNER JOIN TICKET t ON t.JOURNEY_ID = j.ID WHERE (r.TRAIN_NUMBER = '#5343' AND j.TIME_OF_DEPARTURE = '2016-07-24 19:10:25' AND t.STATE = 1) GROUP BY t.TYPE_WAGON;

2: SELECT r.DEPARTURE_POINT, COUNT(r.*) FROM JOURNEY j INNER JOIN ROUTE r ON j.ROUTE_ID = r.ID INNER JOIN TICKET t ON t.JOURNEY_ID = j.ID WHERE (j.TIME_OF_DEPARTURE = '2016-07-24 19:10:25') GROUP BY r.DEPARTURE_POINT;

3: SELECT t.TYPE_WAGON, COUNT(t.*) FROM JOURNEY j INNER JOIN ROUTE r ON j.ROUTE_ID = r.ID INNER JOIN TICKET t ON t.JOURNEY_ID = j.ID WHERE (r.TRAIN_NUMBER = '#5341' AND j.TIME_OF_DEPARTURE = '2016-07-22 19:10:25') GROUP BY t.TYPE_WAGON;

4: SELECT r.TRAIN_NUMBER, COUNT(t.*) FROM JOURNEY j INNER JOIN ROUTE r ON j.ROUTE_ID = r.ID INNER JOIN TICKET t ON t.JOURNEY_ID = j.ID WHERE (j.TIME_OF_DEPARTURE = '2016-07-22 19:10:25' AND t.TYPE_WAGON = 1 AND t.STATE = 1) GROUP BY r.TRAIN_NUMBER HAVING COUNT(t.*) < 10;

5: SELECT t.TYPE_WAGON, ROUND(AVG(t.PRICE), 2) FROM JOURNEY j INNER JOIN ROUTE r ON j.ROUTE_ID = r.ID INNER JOIN TICKET t ON t.JOURNEY_ID = j.ID WHERE (r.DEPARTURE_POINT = 2 AND r.ARRIVAL_POINT = 3 AND j.TIME_OF_DEPARTURE = '2016-07-22 19:10:25') GROUP BY t.TYPE_WAGON;

6: SELECT r.TRAIN_NUMBER, COUNT(t.*) FROM JOURNEY j INNER JOIN ROUTE r ON j.ROUTE_ID = r.ID INNER JOIN TICKET t ON t.JOURNEY_ID = j.ID WHERE (( t.PLACE % 2 ) != 0 AND r.TRAIN_NUMBER = '#5341' AND j.TIME_OF_DEPARTURE = '2016-07-22 19:10:25') GROUP BY r.TRAIN_NUMBER;

7: SELECT r.TRAIN_NUMBER, w.TIME_OF_ARRIVAL, MIN(t.PRICE) as MIN_PRICE FROM JOURNEY j INNER JOIN ROUTE r ON j.ROUTE_ID = r.ID INNER JOIN TICKET t ON t.JOURNEY_ID = j.ID INNER JOIN WAY_STATION w ON w.JOURNEY_ID = j.ID WHERE (w.TIME_OF_ARRIVAL = '2016-07-24 21:10:25' AND w.CITY_ID = 5) GROUP BY r.TRAIN_NUMBER, w.TIME_OF_ARRIVAL;

8: SELECT r.TRAIN_NUMBER, t.TYPE_WAGON, MIN(t.PRICE) as MIN_PRICE, MAX(t.PRICE) as MAX_PRICE FROM JOURNEY j INNER JOIN ROUTE r ON j.ROUTE_ID = r.ID INNER JOIN TICKET t ON t.JOURNEY_ID = j.ID WHERE (r.TRAIN_NUMBER = '#5341' AND j.TIME_OF_DEPARTURE = '2016-07-22 19:10:25' AND t.STATE = 1) GROUP BY r.TRAIN_NUMBER, t.TYPE_WAGON HAVING COUNT(t.*) > 0;

9: SELECT ceil(t.PLACE / 4.0) as KYPE_NUMBER, r.TRAIN_NUMBER, COUNT(CASE WHEN MOD(t.PLACE, 2) != 0 THEN 1 END) AS COUNT_BOTTOM, COUNT(CASE WHEN MOD(t.PLACE, 2) = 0 THEN 1 END) AS COUNT_TOP FROM JOURNEY j INNER JOIN ROUTE r ON j.ROUTE_ID = r.ID INNER JOIN TICKET t ON t.JOURNEY_ID = j.ID WHERE (r.TRAIN_NUMBER = '#5341' AND j.TIME_OF_DEPARTURE = '2016-07-22 19:10:25' AND t.TYPE_WAGON = 2) GROUP BY KYPE_NUMBER, r.TRAIN_NUMBER;
